config/routes.rb
Rails.application.routes.draw do
  
  root to:'welcome#index'

  #### Accounted #####
  get "connecting", to:'accounted#signInMember'
  get "adhesion-partner", to:'accounted#signUpMember'
  get "admin-accounted", to:'accounted#signUpAdmin'

  
  # CAMPAGNES
  get "nouvelle-campagnes", to:"campagnes#new"
  get "campagnes-list", to:"campagnes#index"
  get "edit-campagnes", to:"campagnes#edit"
  #get "campagnes", to:"campagnes#show"
  
  #PROJETS
  get "new-projet", to:"projets#new"
  get "projets-list", to:"projets#index"
  get "edit-projets", to:"projets#edit"
  #get "projets-show", to:"projets#show"
  
  # MEMBERSHIP
  get "adherer", to:'membership#index'
  get "members-list", to:"membership#memberslist"
  get "beaction", to:"membership#beaction"

  #DASHBOARD
  get "dashboard", to:'dashboard#index'
  get "parametrage", to:'dashboard#home'
  get "donate", to:'donate#index'
  get "agisons-ensemble", to:"involved#index"
  
  #ABOUTS
  get "mission", to:"abouts#show"
  get "nous-decouvrir", to:"abouts#index"
  get "mission_new", to:"abouts#new"
  get "mission_editer", to:"abouts#edit"
  get "mission_supprimer", to:"abouts#destroy"
  
  resources :campagnes#, only: %i[ show update destroy]
  resources :abouts, only: %i[create show]
  resources :projets
  resources :works
  resources :newletters

  devise_scope :user do
    get 'profile/edit'    => 'devise/registrations#edit',   :as => :edit_user_registration
    get 'profile/cancel'  => 'devise/registrations#cancel', :as => :cancel_user_registration
    #get '/users/sign_out' => 'devise/sessions#destroy'
  end


  devise_for  :users,
    :path => '',
    :path_names =>
      { :sign_in => 'connected',
        :sign_out => 'logout',
        :sign_up =>   '', :registration => 'adhesion',
        :edit => 'edit'
      }
         
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/campagne.rb
class Campagne < ApplicationRecord
  belongs_to :user
  has_one_attached :heroImg
  has_rich_text :content
  
  Campagne.all.with_rich_text_content # Preload the body without attachments.
  Campagne.all.with_rich_text_content_and_embeds # Preload both body and attachments.


  STATUS= ["Encours", "Approbation", "Public", "La lune", "Archive" ]
  validates :title, :content, :start_date, :amount, presence: true
  #validates_comparison_of :start_date, greater_than: -> { Date.today }
  validates :title, :content, length: { minimum:5}


  ################## SLUG ###############
  extend FriendlyId
  friendly_id :title, use: :slugged
  
  def should_generate_new_friendly_id?
   title_changed?
  end
end

app/controllers/campagnes_controller.rb
class CampagnesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_campagne, only: %i[ show edit update destroy ]

  # GET /campagnes or /campagnes.json
  def index
    @CampagnesList = Campagne.all.order('created_at desc')
    @MembersList = User.membership
    @CampagnesMonthly = @CampagnesList.monthlyActif
    @CampagnesWeekly = @CampagnesMonthly.weeklyActif
    
  end

  # GET /campagnes/1 or /campagnes/1.json
  def show
  end

  # GET /campagnes/new
  def new
    @campagne = Campagne.new
  end

  # GET /campagnes/1/edit
  def edit
  end

  # POST /campagnes or /campagnes.json
  def create
    @campagne = current_user.campagnes.build(campagne_params)

    respond_to do |format|
      if @campagne.save
        format.html { redirect_to campagne_url(@campagne), notice: "Votre campagne est envoyée aux  administrateurs pour l'approbation." }
        format.json { render :show, status: :created, location: @campagne }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @campagne.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campagnes/1 or /campagnes/1.json
  def update
    respond_to do |format|
      if @campagne.update(campagne_params)
        format.html { redirect_to campagne_url(@campagne), notice: "Campagne was successfully updated." }
        format.json { render :show, status: :ok, location: @campagne }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @campagne.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campagnes/1 or /campagnes/1.json
  def destroy
    @campagne.destroy

    respond_to do |format|
      format.html { redirect_to campagnes_url, notice: "Campagne was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campagne
      @campagne = Campagne.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def campagne_params
      params.require(:campagne).permit(:title, :heroImg, :content, :start_date, :slug, :status, :amount, :user_id)
    end
end

app/helpers/campagnes_helper.rb
module CampagnesHelper
end

app/views/campagnes/shared/_campagnes-list.html.erb
<% @title="Liste des campagnes" %>
<!-- component -->

<section class="h-screen w-screen bg-gradient-to-br from-pink-50 to-indigo-100 p-8">
    <h1 class="text-center font-bold text-2xl text-indigo-500">Liste des campagnes </h1>

    <div class="grid justify-center md:grid-cols-2 lg:grid-cols-3 gap-5 lg:gap-7 my-10">
        <!-- Card 1 -->
        <% @CampagnesList.each do |camp| %>
            <div class="bg-white rounded-lg border shadow-md max-w-xs md:max-w-none overflow-hidden">
                <%= camp.heroImg%>
        
                <div class="p-3">
                    <span class="text-sm text-primary"><%= camp.start_date %></span>
                    <h3 class="font-semibold text-xl leading-6 text-gray-700 my-2">
                    <%= camp.title %>
                    </h3>
                    <p class="paragraph-normal text-gray-600">
                    <%= camp.content %>
                    </p>
                    
                    <%= link_to 'Lire plus >>', campagne_path(camp), class:"mt-3 block" %>
                </div>
            </div>
        <% end %>
        
    </div>
</section>

app/views/campagnes/shared/_statistics.html.erb
<div class="mt-4">
    <div class="flex flex-wrap -mx-6">
        <div class="w-full px-6 sm:w-1/2 xl:w-1/3">
            <div class="flex items-center px-5 py-6 shadow-sm rounded-md bg-white">
                <div class="p-3 rounded-full bg-indigo-600 bg-opacity-75">
                    <svg class="h-8 w-8 text-white" viewBox="0 0 28 30" fill="none"
                        xmlns="http://www.w3.org/2000/svg">
                            <path
                                d="M18.2 9.08889C18.2 11.5373 16.3196 13.5222 14 13.5222C11.6804 13.5222 9.79999 11.5373 9.79999 9.08889C9.79999 6.64043 11.6804 4.65556 14 4.65556C16.3196 4.65556 18.2 6.64043 18.2 9.08889Z"
                                fill="currentColor"></path>
                            <path
                                 d="M25.2 12.0444C25.2 13.6768 23.9464 15 22.4 15C20.8536 15 19.6 13.6768 19.6 12.0444C19.6 10.4121 20.8536 9.08889 22.4 9.08889C23.9464 9.08889 25.2 10.4121 25.2 12.0444Z"
                                 fill="currentColor"></path>
                            <path
                                d="M19.6 22.3889C19.6 19.1243 17.0927 16.4778 14 16.4778C10.9072 16.4778 8.39999 19.1243 8.39999 22.3889V26.8222H19.6V22.3889Z"
                                fill="currentColor"></path>
                            <path
                                d="M8.39999 12.0444C8.39999 13.6768 7.14639 15 5.59999 15C4.05359 15 2.79999 13.6768 2.79999 12.0444C2.79999 10.4121 4.05359 9.08889 5.59999 9.08889C7.14639 9.08889 8.39999 10.4121 8.39999 12.0444Z"
                                fill="currentColor"></path>
                            <path
                                d="M6.64896 18.0949C5.98058 19.3671 5.59999 20.8312 5.59999 22.3889V26.8222H1.39999V22.3889C1.39999 19.9404 3.2804 17.9556 5.59999 17.9556C5.96219 17.9556 6.31367 18.0039 6.64896 18.0949Z"
                                fill="currentColor"></path>
                    </svg>
                </div>
    
                <div class="mx-2">
                    <h4 class="text-2xl font-semibold text-gray-700"><%= @CampagnesList.count %> </h4>
                    <div class="text-gray-500">Campagnes - <%= link_to "Créer", "nouvelle-campagnes", class:"font-semibold" %></div>
                </div>
            </div>
            
        <path
             d="M22.4 26.8222V22.3889C22.4 20.8312 22.0195 19.3671 21.351 18.0949C21.6863 18.0039 22.0378 17.9556 22.4 17.9556C24.7197 17.9556 26.6 19.9404 26.6 22.3889V26.8222H22.4Z"
            fill="currentColor"></path>
    </div>
    
    <div class="w-full mt-6 px-6 sm:w-1/2 xl:w-1/3 sm:mt-0">
        <div class="flex items-center px-5 py-6 shadow-sm rounded-md bg-white">
            <div class="p-3 rounded-full bg-orange-600 bg-opacity-75">
                <svg class="h-8 w-8 text-white" viewBox="0 0 28 28" fill="none"
                    xmlns="http://www.w3.org/2000/svg">
                    <path
                        d="M4.19999 1.4C3.4268 1.4 2.79999 2.02681 2.79999 2.8C2.79999 3.57319 3.4268 4.2 4.19999 4.2H5.9069L6.33468 5.91114C6.33917 5.93092 6.34409 5.95055 6.34941 5.97001L8.24953 13.5705L6.99992 14.8201C5.23602 16.584 6.48528 19.6 8.97981 19.6H21C21.7731 19.6 22.4 18.9732 22.4 18.2C22.4 17.4268 21.7731 16.8 21 16.8H8.97983L10.3798 15.4H19.6C20.1303 15.4 20.615 15.1004 20.8521 14.6261L25.0521 6.22609C25.2691 5.79212 25.246 5.27673 24.991 4.86398C24.7357 4.45123 24.2852 4.2 23.8 4.2H8.79308L8.35818 2.46044C8.20238 1.83722 7.64241 1.4 6.99999 1.4H4.19999Z"
                        fill="currentColor"></path>
                    <path
                        d="M22.4 23.1C22.4 24.2598 21.4598 25.2 20.3 25.2C19.1403 25.2 18.2 24.2598 18.2 23.1C18.2 21.9402 19.1403 21 20.3 21C21.4598 21 22.4 21.9402 22.4 23.1Z"
                        fill="currentColor"></path>
                    <path
                        d="M9.1 25.2C10.2598 25.2 11.2 24.2598 11.2 23.1C11.2 21.9402 10.2598 21 9.1 21C7.9402 21 7 21.9402 7 23.1C7 24.2598 7.9402 25.2 9.1 25.2Z"
                        fill="currentColor"></path>
                </svg>
            </div>
    
            <div class="mx-5">
                <h4 class="text-2xl font-semibold text-gray-700"><%=  @CampagnesMonthly.count %></h4>
                <div class="text-gray-500">Mois</div>
            </div>
        </div>
    </div>
    
    <div class="w-full mt-6 px-6 sm:w-1/2 xl:w-1/3 xl:mt-0">
        <div class="flex items-center px-5 py-6 shadow-sm rounded-md bg-white">
            <div class="p-3 rounded-full bg-pink-600 bg-opacity-75">
                <svg class="h-8 w-8 text-white" viewBox="0 0 28 28" fill="none"
                    xmlns="http://www.w3.org/2000/svg">
                    <path d="M6.99998 11.2H21L22.4 23.8H5.59998L6.99998 11.2Z" fill="currentColor"
                        stroke="currentColor" stroke-width="2" stroke-linejoin="round"></path>
                    <path
                        d="M9.79999 8.4C9.79999 6.08041 11.6804 4.2 14 4.2C16.3196 4.2 18.2 6.08041 18.2 8.4V12.6C18.2 14.9197 16.3196 16.8 14 16.8C11.6804 16.8 9.79999 14.9197 9.79999 12.6V8.4Z"
                        stroke="currentColor" stroke-width="2"></path>
                </svg>
            </div>
    
            <div class="mx-5">
                <h4 class="text-2xl font-semibold text-gray-700"><%= @CampagnesWeekly.count %></h4>
                <div class="text-gray-500">Semaine</div>
            </div>
        </div>
    </div>
    </div>
</div>
    