config/routes.rb
Rails.application.routes.draw do
  
  root to:'welcome#index'

  #### Accounted #####
  get "connecting", to:'accounted#signInMember'
  get "adhesion-partner", to:'accounted#signUpMember'
  get "admin-accounted", to:'accounted#signUpAdmin'

  
  # CAMPAGNES
  get "nouvelle-campagnes", to:"campagnes#new"
  get "campagnes-list", to:"campagnes#index"
  get "edit-campagnes", to:"campagnes#edit"
  #get "campagnes", to:"campagnes#show"
  
  #PROJETS
  get "new-projet", to:"projets#new"
  get "projets-list", to:"projets#index"
  get "edit-projets", to:"projets#edit"
  #get "projets-show", to:"projets#show"
  
  # MEMBERSHIP
  get "adherer", to:'membership#index'
  get "members-list", to:"membership#memberslist"
  get "beaction", to:"membership#beaction"

  #DASHBOARD
  get "dashboard", to:'dashboard#index'
  get "parametrage", to:'dashboard#home'
  get "donate", to:'donate#index'
  get "agisons-ensemble", to:"involved#index"
  
  #ABOUTS
  get "mission", to:"abouts#show"
  get "nous-decouvrir", to:"abouts#index"
  get "mission_new", to:"abouts#new"
  get "mission_editer", to:"abouts#edit"
  get "mission_supprimer", to:"abouts#destroy"
  
  resources :campagnes#, only: %i[ show update destroy]
  resources :abouts, only: %i[create show]
  resources :projets
  resources :works
  resources :newletters

  devise_scope :user do
    get 'profile/edit'    => 'devise/registrations#edit',   :as => :edit_user_registration
    get 'profile/cancel'  => 'devise/registrations#cancel', :as => :cancel_user_registration
    #get '/users/sign_out' => 'devise/sessions#destroy'
  end


  devise_for  :users,
    :path => '',
    :path_names =>
      { :sign_in => 'connected',
        :sign_out => 'logout',
        :sign_up =>   '', :registration => 'adhesion',
        :edit => 'edit'
      }
         
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/projet.rb
class Projet < ApplicationRecord
  belongs_to :user
  has_rich_text :content
  #Projet.all.with_rich_text_content # Preload the body without attachments.
  #Projet.all.with_rich_text_content_and_embeds # Preload both body and attachments.


  STATUS= ["Encours", "Approbation", "Public", "La lune", "Archive" ]
  validates :title, :content, :start_date, :amount, presence: true
  validates :title, :content, length: { minimum:5}


  ################## SLUG ###############
  extend FriendlyId
  friendly_id :title, use: :slugged
  
  def should_generate_new_friendly_id?
   title_changed?
  end
end

app/controllers/projets_controller.rb
class ProjetsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_projet, only: %i[ show edit update destroy ]

  # GET /projets or /projets.json
  def index
    @MembersList = User.membership
    @ProjetsList = Projet.all.order('created_at desc')
    @ProjetsMonthly = @ProjetsList.monthlyActif
    @ProjetsWeekly = @ProjetsMonthly.weeklyActif
  end

  # GET /projets/1 or /projets/1.json
  def show
  end

  # GET /projets/new
  def new
    @projet = Projet.new
  end

  # GET /projets/1/edit
  def edit
  end

  # POST /projets or /projets.json
  def create
    @projet = current_user.projets.build(projet_params)

    respond_to do |format|
      if @projet.save
        format.html { redirect_to projet_url(@projet), notice: "Projet est bien enregistré." }
        format.json { render :show, status: :created, location: @projet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @projet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projets/1 or /projets/1.json
  def update
    respond_to do |format|
      if @projet.update(projet_params)
        format.html { redirect_to projet_url(@projet), notice: "Projet was successfully updated." }
        format.json { render :show, status: :ok, location: @projet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @projet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projets/1 or /projets/1.json
  def destroy
    @projet.destroy

    respond_to do |format|
      format.html { redirect_to projets_url, notice: "Projet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_projet
      @projet = Projet.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def projet_params
      params.require(:projet).permit(:title, :heroImg, :content, :start_date, :amount, :status, :slug, :user_id)
    end
end

app/helpers/projets_helper.rb
module ProjetsHelper
end

app/views/projets/_form.html.erb
<%= bootstrap_form_for(@projet,  inline_errors: true) do |f| %>
 
  <div class="form-inputs">
    <%= f.text_field  :title, label:"Nom du Projet", class:"p-2 border rounded-md", placeholder:'Nom du projet ...', help:"Plus nom reflete la cause que vous deffendez, mieux les autres adheront"  %>
  </div>
  
  <div class="">
    <%= f.rich_text_area :content, hide_label:true, class:" bg-red-500 border rounded-md ", placeholder:'Contenu du projet ...' %>
  </div>
  <div class="">
    <%= f.file_field :heroImg %>
  </div>

  <div class="group">
    <%= f.date_field :start_date, class:" p-2 border rounded-md" %>
    <%= f.select :status, Projet::STATUS, class:"p-6 border border-bblue-500 rounded-md", placeholder:'Status...' %>
  </div>
  <div class="">
    
      <%= f.text_field :amount, prepend: ['Net Extimé', '€'], append: ['.00', 'pour le projet'], hide_label:true , placeholder:"montant ...", class:"p-2 border outline-none rounded-md" %>
  </div>
      

  <div class="form-actions">
    <%= f.submit "Créer Projet", class:"p-2 border rounded-md bg-green-500 font-semibold text-white my-2" %>
  </div>
<% end %>

app/views/projets/_projet.html.erb
<div id="<%= dom_id projet %>">
  <div class="container bg-white border-1 rounded-md m-2 ">
    <p>
      <strong>Title:</strong>
      <%= projet.title %>
    </p>

    <p>
      <strong>Heroimg:</strong>
      <%= projet.heroImg %>
    </p>

    <p>
      <strong>Content:</strong>
      <%= projet.content %>
    </p>

    <p>
      <strong>Start date:</strong>
      <%= projet.start_date %>
    </p>

    <p>
      <strong>Amount:</strong>
      <%= projet.amount %>
    </p>
    <strong>Status:</strong>
    <span class="font-bold"> <%= projet.status %>  </span> d'approbation
    <p>
      <strong>Auteur:</strong>
      <%= projet.user.full_name %>
    </p>

  </div>
</div>

app/views/projets/edit.html.erb
<h1>Editing projet</h1>

<%= render "form", projet: @projet %>

<br>

<div>
  <%= link_to "Show this projet", @projet %> |
  <%= link_to "Back to projets", projets_path %>
</div>

app/views/projets/index.html.erb
<!-- component -->
<div>
    <div x-data="{ sidebarOpen: false }" class="flex h-screen bg-gray-200">
        <div :class="sidebarOpen ? 'block' : 'hidden'" @click="sidebarOpen = false" class="fixed z-20 inset-0 bg-black opacity-50 transition-opacity lg:hidden"></div>
        <!-- Sidebar -->
        <%= render "dashboard/shared/sidebar" %>
          
        <div class="flex-1 flex flex-col overflow-hidden">
        <!-- Header -->
        <%= render "dashboard/shared/header" %>
            <main class="flex-1 overflow-x-hidden overflow-y-auto bg-gray-200">
                <div class="container mx-auto px-6 py-8">
                    <h3 class="text-gray-700 text-2xl font-medium">Tableau de bord</h3>
                    <div class="mt-8">
                        <!-- Header -->
                        <%= render "projets/shared/statistics" %>
                    </div>
    
                    <div class="flex flex-col mt-8">
                   
                        <%= render "projets/shared/projets-list" %>
                    </div>
                </div>
            </main>
        </div>
    </div>
</div>

app/views/projets/new.html.erb
<% @title="Nouveau projet" %>
<!-- component -->
<div>
    <div x-data="{ sidebarOpen: false }" class="flex h-screen bg-gray-200">
        <div :class="sidebarOpen ? 'block' : 'hidden'" @click="sidebarOpen = false" class="fixed z-20 inset-0 bg-black opacity-50 transition-opacity lg:hidden"></div>
        <!-- Sidebar -->
        <%= render "dashboard/shared/sidebar" %>
          
        <div class="flex-1 flex flex-col overflow-hidden">
        <!-- Header -->
        <%= render "dashboard/shared/header" %>
            <main class="flex-1 overflow-x-hidden overflow-y-auto bg-gray-200">
                <div class="container mx-auto px-6 py-8">
                
                    <div class="flex flex-col mt-8">
                    <h3 class="text-gray-700 text-2xl font-medium">Nouveau Projet</h3>
                    <%=  %>
                      <%= render "form", projet: @projet %>
                    </div>
                </div>
            </main>
        </div>
    </div>
</div>

app/views/projets/show-draft.html.erb
<!-- component -->
<div class="flex justify-center items-center">
  <!--- more free and premium Tailwind CSS components at https://tailwinduikit.com/ --->
  <div class="2xl:mx-auto 2xl:container lg:px-20 lg:py-16 md:py-12 md:px-6 py-9 px-4 w-96 sm:w-auto">
    <div role="main" class="flex flex-col items-center justify-center">
      <h1 class="text-4xl font-semibold leading-9 text-center text-gray-800 dark:text-gray-50">This Week Blogs</h1>
      <p class="text-base leading-normal text-center text-gray-600 dark:text-white mt-4 lg:w-1/2 md:w-10/12 w-11/12">If you're looking for random paragraphs, you've come to the right place. When a random word or a random sentence isn't quite enough</p>
    </div>
    <div class="lg:flex items-stretch md:mt-12 mt-8">
      <div class="lg:w-1/2">
        <div class="sm:flex items-center justify-between xl:gap-x-8 gap-x-6">
          <div class="sm:w-1/2 relative">
            <div>
              <p class="p-6 text-xs font-medium leading-3 text-white absolute top-0 right-0">12 April 2021</p>
              <div class="absolute bottom-0 left-0 p-6">
                <h2 class="text-xl font-semibold 5 text-white">The Decorated Ways</h2>
                <p class="text-base leading-4 text-white mt-2">Dive into minimalism</p>
                <a href="javascript:void(0)" class="focus:outline-none focus:underline flex items-center mt-4 cursor-pointer text-white hover:text-gray-200 hover:underline">
                  <p class="pr-2 text-sm font-medium leading-none">Read More</p>
                  <svg class="fill-stroke" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M5.75 12.5L10.25 8L5.75 3.5" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                  </svg>
                </a>
              </div>
            </div>
            <img src="https://i.ibb.co/DYxtCJq/img-1.png" class="w-full" alt="chair" />
          </div>
          <div class="sm:w-1/2 sm:mt-0 mt-4 relative">
            <div>
              <p class="p-6 text-xs font-medium leading-3 text-white absolute top-0 right-0">12 April 2021</p>
              <div class="absolute bottom-0 left-0 p-6">
                <h2 class="text-xl font-semibold 5 text-white">The Decorated Ways</h2>
                <p class="text-base leading-4 text-white mt-2">Dive into minimalism</p>
                <a href="javascript:void(0)" class="focus:outline-none focus:underline flex items-center mt-4 cursor-pointer text-white hover:text-gray-200 hover:underline">
                  <p class="pr-2 text-sm font-medium leading-none">Read More</p>
                  <svg class="fill-stroke" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M5.75 12.5L10.25 8L5.75 3.5" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                  </svg>
                </a>
              </div>
            </div>
            <img src="https://i.ibb.co/3C5HvxC/img-2.png" class="w-full" alt="wall design" />
          </div>
        </div>
        <div class="relative">
          <div>
            <p class="md:p-10 p-6 text-xs font-medium leading-3 text-white absolute top-0 right-0">12 April 2021</p>
            <div class="absolute bottom-0 left-0 md:p-10 p-6">
              <h2 class="text-xl font-semibold 5 text-white">The Decorated Ways</h2>
              <p class="text-base leading-4 text-white mt-2">Dive into minimalism</p>
              <a href="javascript:void(0)" class="focus:outline-none focus:underline flex items-center mt-4 cursor-pointer text-white hover:text-gray-200 hover:underline">
                <p class="pr-2 text-sm font-medium leading-none">Read More</p>
                <svg class="fill-stroke" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path d="M5.75 12.5L10.25 8L5.75 3.5" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                </svg>
              </a>
            </div>
          </div>
          <img src="https://i.ibb.co/Ms4qyXp/img-3.png" alt="sitting place" class="w-full mt-8 md:mt-6 hidden sm:block" />
          <img class="w-full mt-4 sm:hidden" src="https://i.ibb.co/6XYbN7f/Rectangle-29.png" alt="sitting place" />
        </div>
      </div>
      <div class="lg:w-1/2 xl:ml-8 lg:ml-4 lg:mt-0 md:mt-6 mt-4 lg:flex flex-col justify-between">
        <div class="relative">
          <div>
            <p class="md:p-10 p-6 text-xs font-medium leading-3 text-white absolute top-0 right-0">12 April 2021</p>
            <div class="absolute bottom-0 left-0 md:p-10 p-6">
              <h2 class="text-xl font-semibold 5 text-white">The Decorated Ways</h2>
              <p class="text-base leading-4 text-white mt-2">Dive into minimalism</p>
              <a href="javascript:void(0)" class="focus:outline-none focus:underline flex items-center mt-4 cursor-pointer text-white hover:text-gray-200 hover:underline">
                <p class="pr-2 text-sm font-medium leading-none">Read More</p>
                <svg class="fill-stroke" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path d="M5.75 12.5L10.25 8L5.75 3.5" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                </svg>
              </a>
            </div>
          </div>
          <img src="https://i.ibb.co/6Wfjf2w/img-4.png" alt="sitting place" class="w-full sm:block hidden" />
          <img class="w-full sm:hidden" src="https://i.ibb.co/dpXStJk/Rectangle-29.png" alt="sitting place" />
        </div>
        <div class="sm:flex items-center justify-between xl:gap-x-8 gap-x-6 md:mt-6 mt-4">
          <div class="relative w-full">
            <div>
              <p class="p-6 text-xs font-medium leading-3 text-white absolute top-0 right-0">12 April 2021</p>
              <div class="absolute bottom-0 left-0 p-6">
                <h2 class="text-xl font-semibold 5 text-white">The Decorated Ways</h2>
                <p class="text-base leading-4 text-white mt-2">Dive into minimalism</p>
                <a href="javascript:void(0)" class="focus:outline-none focus:underline flex items-center mt-4 cursor-pointer text-white hover:text-gray-200 hover:underline">
                  <p class="pr-2 text-sm font-medium leading-none">Read More</p>
                  <svg class="fill-stroke" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M5.75 12.5L10.25 8L5.75 3.5" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                  </svg>
                </a>
              </div>
            </div>
            <img src="https://i.ibb.co/3yvZBpm/img-5.png" class="w-full" alt="chair" />
          </div>
          <div class="relative w-full sm:mt-0 mt-4">
            <div>
              <p class="p-6 text-xs font-medium leading-3 text-white absolute top-0 right-0">12 April 2021</p>
              <div class="absolute bottom-0 left-0 p-6">
                <h2 class="text-xl font-semibold 5 text-white">The Decorated Ways</h2>
                <p class="text-base leading-4 text-white mt-2">Dive into minimalism</p>
                <a href="javascript:void(0)" class="focus:outline-none focus:underline flex items-center mt-4 cursor-pointer text-white hover:text-gray-200 hover:underline">
                  <p class="pr-2 text-sm font-medium leading-none">Read More</p>
                  <svg class="fill-stroke" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M5.75 12.5L10.25 8L5.75 3.5" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                  </svg>
                </a>
              </div>
            </div>
            <img src="https://i.ibb.co/gDdnJb5/img-6.png" class="w-full" alt="wall design" />
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projets/show.html.erb
<% @title= @projet.title %>
<!-- component -->
<div>
    <div x-data="{ sidebarOpen: false }" class="flex h-screen bg-gray-200">
        <div :class="sidebarOpen ? 'block' : 'hidden'" @click="sidebarOpen = false" class="fixed z-20 inset-0 bg-black opacity-50 transition-opacity lg:hidden"></div>
        <!-- Sidebar -->
        <%= render "dashboard/shared/sidebar" %>
          
        <div class="flex-1 flex flex-col overflow-hidden">
        <!-- Header -->
        <%= render "dashboard/shared/header" %>
            <main class="flex-1 overflow-x-hidden overflow-y-auto bg-gray-200">
                <div class="container mx-auto px-6 py-8">
                    <h3 class="text-gray-700 text-2xl font-medium">Tableau de bord</h3>
                      <%= render_notification %>
                       
                    <div class="flex flex-col mt-8">
                    <h3 class="text-gray-700 text-2xl font-medium">Liste Projet</h3>
                      <%= render @projet %>
                        
                        <div>
                            <%= link_to "Editer", edit_projet_path(@projet) %> |            
                            <div class="flex-initial">
                                <%= button_to  @projet, method: :delete, 
                                    class:"flex items-center px-5 py-2.5 font-medium tracking-wide text-black
                                    capitalize rounded-md  hover:bg-red-200 hover:fill-current hover:text-red-600
                                    focus:outline-none  transition duration-300 transform active:scale-95 ease-in-out" do %>
                                    <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px">
                                        <path d="M0 0h24v24H0V0z" fill="none"></path>
                                        <path d="M8 9h8v10H8z" opacity=".3"></path>
                                        <path d="M15.5 4l-1-1h-5l-1 1H5v2h14V4zM6 19c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V7H6v12zM8 9h8v10H8V9z"></path>
                                    </svg>
                                    <span class="pl-2 mx-1">Supprimer</span>
                                <% end %>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    </div>
</div>